version: '3'
services:
  web:
    build: ./
    ports:
      - 81:81
    volumes:
      - ./:/usr/share/nginx/html

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=mywebapp
      - MYSQL_DATABASE=mydb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
